/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/h2VVL6gc4uF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"

export function AcordionEl() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="mx-auto max-w-3xl space-y-4">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Frequently Asked Questions</h2>
          <p className="text-gray-500 dark:text-gray-400">
            Find answers to the most common questions about our product. If you can't find what you're looking for, feel
            free to contact us.
          </p>
          <div className="space-y-2">
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-sm font-medium transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:bg-gray-700">
                <span>What is the pricing structure?</span>
                <CollapsibleTrigger asChild>
                  <Button size="sm" variant="ghost">
                    <ChevronDownIcon className="h-4 w-4 transition-transform data-[state=open]:rotate-180" />
                  </Button>
                </CollapsibleTrigger>
              </CollapsibleTrigger>
              <CollapsibleContent className="rounded-md border border-gray-200 bg-white p-4 text-sm text-gray-500 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-400">
                Our pricing is based on the number of users and the features you need. We offer a range of plans to suit
                different business sizes and requirements. You can check our pricing page for more details.
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-sm font-medium transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:bg-gray-700">
                <span>How do I get started?</span>
                <CollapsibleTrigger asChild>
                  <Button size="sm" variant="ghost">
                    <ChevronDownIcon className="h-4 w-4 transition-transform data-[state=open]:rotate-180" />
                  </Button>
                </CollapsibleTrigger>
              </CollapsibleTrigger>
              <CollapsibleContent className="rounded-md border border-gray-200 bg-white p-4 text-sm text-gray-500 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-400">
                Getting started is easy! Simply sign up for an account on our website and follow the onboarding
                instructions. Our team is available to help you every step of the way.
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-sm font-medium transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:bg-gray-700">
                <span>What kind of support do you offer?</span>
                <CollapsibleTrigger asChild>
                  <Button size="sm" variant="ghost">
                    <ChevronDownIcon className="h-4 w-4 transition-transform data-[state=open]:rotate-180" />
                  </Button>
                </CollapsibleTrigger>
              </CollapsibleTrigger>
              <CollapsibleContent className="rounded-md border border-gray-200 bg-white p-4 text-sm text-gray-500 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-400">
                We offer a variety of support options, including email, live chat, and phone support. Our team of
                experts is available to assist you with any questions or issues you may have. We also have a
                comprehensive knowledge base and documentation to help you get the most out of our product.
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-sm font-medium transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:bg-gray-700">
                <span>How secure is my data?</span>
                <CollapsibleTrigger asChild>
                  <Button size="sm" variant="ghost">
                    <ChevronDownIcon className="h-4 w-4 transition-transform data-[state=open]:rotate-180" />
                  </Button>
                </CollapsibleTrigger>
              </CollapsibleTrigger>
              <CollapsibleContent className="rounded-md border border-gray-200 bg-white p-4 text-sm text-gray-500 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-400">
                We take data security very seriously. Your data is encrypted at rest and in transit, and we have robust
                security measures in place to protect it from unauthorized access. We also comply with industry-standard
                security and privacy regulations.
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-sm font-medium transition-colors hover:bg-gray-200 focus:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:bg-gray-700">
                <span>Can I integrate your product with my existing systems?</span>
                <CollapsibleTrigger asChild>
                  <Button size="sm" variant="ghost">
                    <ChevronDownIcon className="h-4 w-4 transition-transform data-[state=open]:rotate-180" />
                  </Button>
                </CollapsibleTrigger>
              </CollapsibleTrigger>
              <CollapsibleContent className="rounded-md border border-gray-200 bg-white p-4 text-sm text-gray-500 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:text-gray-400">
                Yes, our product is designed to be highly flexible and customizable. We offer a range of integration
                options, including APIs, webhooks, and pre-built connectors, to help you seamlessly integrate our
                product with your existing systems and workflows.
              </CollapsibleContent>
            </Collapsible>
          </div>
        </div>
      </div>
    </section>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
